### PR TITLE
Add WebAssembly language and Wasm3 engine

### PR DESCRIPTION
**Pull request by vshymanskyy**
Yes, WebAssembly. `Wasm3` is a WebAssembly interpreter, that enables WebAssembly self-hosting.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
@appcypher any chance to merge this soon? Thx ;)

**Comment by appcypher** [comment]
Thanks for contributing, but this a list of languages not wasm engines.
For that you can check the list [here](https://github.com/appcypher/awesome-wasm-runtimes).
Sorry for replying late.

**Comment by vshymanskyy** [comment]
Sorry, I believe you didn't get it right ;)
WebAssembly itself can be viewed as a language, and it can run under WebAssembly.
Hope that clarifies things.

**Comment by dullbananas** [comment]
>  WebAssembly itself can be viewed as a language, and it can run under WebAssembly.

So is it similar to how normal assembly compiles to machine code?

**Comment by vshymanskyy** [comment]
It's similar to say, have Python language implemented in Python 😁

**Comment by appcypher** [comment]
What you said would make sense if your wasm interpreter had a version compiled to wasm. Or if it compiles to wasm 🤔which is kinda recursive.

**Comment by vshymanskyy** [comment]
@appcypher Actually, **it is** ;)
Check out Wasm3 on Webassembly.sh: https://webassembly.sh/?run-command=wasm3
As well as this example: https://twitter.com/wasm3_engine/status/1229569441010196480

**Comment by appcypher** [comment]
Nice! I'm going to update the readme

**Comment by vshymanskyy** [comment]
@appcypher, wondering if you're still considering to add this.

**Comment by appcypher** [comment]
Sorry for the late reply.
I'm adding it now. I haven't been following wasm lately.

**Pull request closed without merging**
